

module AbsPetit where

-- Haskell module generated by the BNF converter




newtype Ident = Ident String deriving (Eq, Ord, Show, Read)
data Program = PDefs [Stm]
  deriving (Eq, Ord, Show, Read)

data Stm = SAss Ident Exp | SFor Exp Stm
  deriving (Eq, Ord, Show, Read)

data Exp = EZer | ESuc Exp | EVar Ident
  deriving (Eq, Ord, Show, Read)

