package petit.Absyn; // Java Package generated by the BNF Converter.

public class ESuc extends Exp {
  public final Exp exp_;

  public ESuc(Exp p1) { exp_ = p1; }

  public <R,A> R accept(petit.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof petit.Absyn.ESuc) {
      petit.Absyn.ESuc x = (petit.Absyn.ESuc)o;
      return this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return this.exp_.hashCode();
  }


}
