package petit.Absyn; // Java Package generated by the BNF Converter.

public abstract class Exp implements java.io.Serializable {
  public abstract <R,A> R accept(Exp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(petit.Absyn.EZer p, A arg);
    public R visit(petit.Absyn.ESuc p, A arg);
    public R visit(petit.Absyn.EVar p, A arg);

  }

}
