package petit.Absyn; // Java Package generated by the BNF Converter.

public class EZer extends Exp {

  public EZer() { }

  public <R,A> R accept(petit.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof petit.Absyn.EZer) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
