package petit.Absyn; // Java Package generated by the BNF Converter.

public class PDefs extends Program {
  public final ListStm liststm_;

  public PDefs(ListStm p1) { liststm_ = p1; }

  public <R,A> R accept(petit.Absyn.Program.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof petit.Absyn.PDefs) {
      petit.Absyn.PDefs x = (petit.Absyn.PDefs)o;
      return this.liststm_.equals(x.liststm_);
    }
    return false;
  }

  public int hashCode() {
    return this.liststm_.hashCode();
  }


}
