
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 07 18:28:11 JST 2013
//----------------------------------------------------

package petit;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int _SYMB_7 = 9;
  public static final int _SYMB_6 = 8;
  public static final int _SYMB_5 = 7;
  public static final int _SYMB_4 = 6;
  public static final int _SYMB_3 = 5;
  public static final int _SYMB_2 = 4;
  public static final int _SYMB_1 = 3;
  public static final int _SYMB_0 = 2;
  public static final int EOF = 0;
  public static final int _IDENT_ = 10;
  public static final int error = 1;
}

